version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8579:8579' # Server port
      - '8580:8580' # Client port
    volumes:
      - sqlite_data:/app/data
    environment:
      - REDIS_URL=redis://redis:6379
      - NODE_ENV=production
    command: bun run start
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 1s
    restart: unless-stopped

volumes:
  redis_data:
  sqlite_data:
